[build]
  command = "npm run build && npm run export"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BACKEND_API = "https://degenagent-backend.onrender.com/api"
  NEXT_PUBLIC_RPC_ENDPOINT = "https://mainnet.helius-rpc.com/?api-key=0609d375-ac29-4da3-be17-5ab640679dd8"
