[toolchain]

[features]
seeds = false
skip-lint = false

[workspace]
members = [
    "programs/agent-registry",
    "programs/agent-manager",
    "programs/agent-factory"
]

[programs.localnet]
agent_registry = "AgentReg1stry1111111111111111111111111111111"

[programs.devnet]
agent_registry = "AgentReg1stry1111111111111111111111111111111"

[programs.mainnet]
agent_registry = "AgentReg1stry1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
